import { ValidDistrict } from 'manchitro';
import { District } from '@/lib/api-client';

export interface StaticDistrictData {
  name: string;
  bnName: string;
  slug: string;
  canonicalName: ValidDistrict;
  division: {
    name: string;
    bnName: string;
    slug: string;
  };
  latitude: number;
  longitude: number;
}

export const ALL_STATIC_DIVISIONS = [
  { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
  { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
  { name: 'Sylhet', bnName: 'সিলেট', slug: 'sylhet' },
  { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
  { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
  { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
  { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
  { name: 'Mymensingh', bnName: 'ময়মনসিংহ', slug: 'mymensingh' },
];

export const ALL_STATIC_DISTRICTS: StaticDistrictData[] = [
  // 1. Chattogram (11)
  {
    name: 'Chattogram',
    bnName: 'চট্টগ্রাম',
    slug: 'chattogram',
    canonicalName: 'Chittagong',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 22.3569,
    longitude: 91.7832,
  },
  {
    name: "Cox's Bazar",
    bnName: 'কক্সবাজার',
    slug: 'coxs-bazar',
    canonicalName: "Cox's Bazar",
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 21.4272,
    longitude: 92.0058,
  },
  {
    name: 'Bandarban',
    bnName: 'বান্দরবান',
    slug: 'bandarban',
    canonicalName: 'Bandarban',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 22.1953,
    longitude: 92.2184,
  },
  {
    name: 'Rangamati',
    bnName: 'রাঙ্গামাটি',
    slug: 'rangamati',
    canonicalName: 'Rangamati',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 22.7324,
    longitude: 92.2985,
  },
  {
    name: 'Khagrachhari',
    bnName: 'খাগড়াছড়ি',
    slug: 'khagrachhari',
    canonicalName: 'Khagrachari',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 23.1193,
    longitude: 91.9847,
  },
  {
    name: 'Cumilla',
    bnName: 'কুমিল্লা',
    slug: 'cumilla',
    canonicalName: 'Comilla',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 23.4682,
    longitude: 91.1788,
  },
  {
    name: 'Feni',
    bnName: 'ফেনী',
    slug: 'feni',
    canonicalName: 'Feni',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 23.0159,
    longitude: 91.3976,
  },
  {
    name: 'Brahmanbaria',
    bnName: 'ব্রাহ্মণবাড়িয়া',
    slug: 'brahmanbaria',
    canonicalName: 'Brahmanbaria',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 23.9608,
    longitude: 91.1115,
  },
  {
    name: 'Noakhali',
    bnName: 'নোয়াখালী',
    slug: 'noakhali',
    canonicalName: 'Noakhali',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 22.8696,
    longitude: 91.0991,
  },
  {
    name: 'Chandpur',
    bnName: 'চাঁদপুর',
    slug: 'chandpur',
    canonicalName: 'Chandpur',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 23.2333,
    longitude: 90.6667,
  },
  {
    name: 'Lakshmipur',
    bnName: 'লক্ষ্মীপুর',
    slug: 'lakshmipur',
    canonicalName: 'Lakshmipur',
    division: { name: 'Chattogram', bnName: 'চট্টগ্রাম', slug: 'chattogram' },
    latitude: 22.9447,
    longitude: 90.8282,
  },

  // 2. Sylhet (4)
  {
    name: 'Sylhet',
    bnName: 'সিলেট',
    slug: 'sylhet',
    canonicalName: 'Sylhet',
    division: { name: 'Sylhet', bnName: 'সিলেট', slug: 'sylhet' },
    latitude: 24.8949,
    longitude: 91.8687,
  },
  {
    name: 'Moulvibazar',
    bnName: 'মৌলভীবাজার',
    slug: 'moulvibazar',
    canonicalName: 'Maulvibazar',
    division: { name: 'Sylhet', bnName: 'সিলেট', slug: 'sylhet' },
    latitude: 24.4829,
    longitude: 91.7774,
  },
  {
    name: 'Sunamganj',
    bnName: 'সুনামগঞ্জ',
    slug: 'sunamganj',
    canonicalName: 'Sunamganj',
    division: { name: 'Sylhet', bnName: 'সিলেট', slug: 'sylhet' },
    latitude: 25.0658,
    longitude: 91.3950,
  },
  {
    name: 'Habiganj',
    bnName: 'হবিগঞ্জ',
    slug: 'habiganj',
    canonicalName: 'Habiganj',
    division: { name: 'Sylhet', bnName: 'সিলেট', slug: 'sylhet' },
    latitude: 24.3749,
    longitude: 91.4155,
  },

  // 3. Dhaka (13)
  {
    name: 'Dhaka',
    bnName: 'ঢাকা',
    slug: 'dhaka',
    canonicalName: 'Dhaka',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.8103,
    longitude: 90.4125,
  },
  {
    name: 'Gazipur',
    bnName: 'গাজীপুর',
    slug: 'gazipur',
    canonicalName: 'Gazipur',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.9999,
    longitude: 90.4203,
  },
  {
    name: 'Narayanganj',
    bnName: 'নারায়ণগঞ্জ',
    slug: 'narayanganj',
    canonicalName: 'Narayanganj',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.6238,
    longitude: 90.5000,
  },
  {
    name: 'Tangail',
    bnName: 'টাঙ্গাইল',
    slug: 'tangail',
    canonicalName: 'Tangail',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 24.2513,
    longitude: 89.9167,
  },
  {
    name: 'Narsingdi',
    bnName: 'নরসিংদী',
    slug: 'narsingdi',
    canonicalName: 'Narshingdi',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.9197,
    longitude: 90.7202,
  },
  {
    name: 'Kishoreganj',
    bnName: 'কিশোরগঞ্জ',
    slug: 'kishoreganj',
    canonicalName: 'Kishoreganj',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 24.4449,
    longitude: 90.7766,
  },
  {
    name: 'Manikganj',
    bnName: 'মানিকগঞ্জ',
    slug: 'manikganj',
    canonicalName: 'Manikganj',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.8617,
    longitude: 90.0003,
  },
  {
    name: 'Munshiganj',
    bnName: 'মুন্সীগঞ্জ',
    slug: 'munshiganj',
    canonicalName: 'Munshiganj',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.5422,
    longitude: 90.5305,
  },
  {
    name: 'Faridpur',
    bnName: 'ফরিদপুর',
    slug: 'faridpur',
    canonicalName: 'Faridpur',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.6071,
    longitude: 89.8429,
  },
  {
    name: 'Gopalganj',
    bnName: 'গোপালগঞ্জ',
    slug: 'gopalganj',
    canonicalName: 'Gopalganj',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.0051,
    longitude: 89.8266,
  },
  {
    name: 'Madaripur',
    bnName: 'মাদারীপুর',
    slug: 'madaripur',
    canonicalName: 'Madaripur',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.1641,
    longitude: 90.1897,
  },
  {
    name: 'Rajbari',
    bnName: 'রাজবাড়ী',
    slug: 'rajbari',
    canonicalName: 'Rajbari',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.7574,
    longitude: 89.6445,
  },
  {
    name: 'Shariatpur',
    bnName: 'শরীয়তপুর',
    slug: 'shariatpur',
    canonicalName: 'Shariatpur',
    division: { name: 'Dhaka', bnName: 'ঢাকা', slug: 'dhaka' },
    latitude: 23.2423,
    longitude: 90.4348,
  },

  // 4. Khulna (10)
  {
    name: 'Khulna',
    bnName: 'খুলনা',
    slug: 'khulna',
    canonicalName: 'Khulna',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 22.8456,
    longitude: 89.5403,
  },
  {
    name: 'Bagerhat',
    bnName: 'বাগেরহাট',
    slug: 'bagerhat',
    canonicalName: 'Bagerhat',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 22.6516,
    longitude: 89.7859,
  },
  {
    name: 'Satkhira',
    bnName: 'সাতক্ষীরা',
    slug: 'satkhira',
    canonicalName: 'Satkhira',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 22.7185,
    longitude: 89.0705,
  },
  {
    name: 'Jashore',
    bnName: 'যশোর',
    slug: 'jashore',
    canonicalName: 'Jessore',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.1664,
    longitude: 89.2137,
  },
  {
    name: 'Kushtia',
    bnName: 'কুষ্টিয়া',
    slug: 'kushtia',
    canonicalName: 'Kushtia',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.9013,
    longitude: 89.1204,
  },
  {
    name: 'Jhenaidah',
    bnName: 'ঝিনাইদহ',
    slug: 'jhenaidah',
    canonicalName: 'Jhinaidaha',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.5448,
    longitude: 89.1539,
  },
  {
    name: 'Chuadanga',
    bnName: 'চুয়াডাঙ্গা',
    slug: 'chuadanga',
    canonicalName: 'Chuadanga',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.6402,
    longitude: 88.8418,
  },
  {
    name: 'Meherpur',
    bnName: 'মেহেরপুর',
    slug: 'meherpur',
    canonicalName: 'Meherpur',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.7622,
    longitude: 88.6318,
  },
  {
    name: 'Magura',
    bnName: 'মাগুরা',
    slug: 'magura',
    canonicalName: 'Magura',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.4873,
    longitude: 89.4198,
  },
  {
    name: 'Narail',
    bnName: 'নড়াইল',
    slug: 'narail',
    canonicalName: 'Narail',
    division: { name: 'Khulna', bnName: 'খুলনা', slug: 'khulna' },
    latitude: 23.1725,
    longitude: 89.5127,
  },

  // 5. Rajshahi (8)
  {
    name: 'Rajshahi',
    bnName: 'রাজশাহী',
    slug: 'rajshahi',
    canonicalName: 'Rajshahi',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.3745,
    longitude: 88.6042,
  },
  {
    name: 'Bogura',
    bnName: 'বগুড়া',
    slug: 'bogura',
    canonicalName: 'Bogra',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.8465,
    longitude: 89.3777,
  },
  {
    name: 'Pabna',
    bnName: 'পাবনা',
    slug: 'pabna',
    canonicalName: 'Pabna',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.0116,
    longitude: 89.2562,
  },
  {
    name: 'Sirajganj',
    bnName: 'সিরাজগঞ্জ',
    slug: 'sirajganj',
    canonicalName: 'Sirajganj',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.4534,
    longitude: 89.7008,
  },
  {
    name: 'Naogaon',
    bnName: 'নওগাঁ',
    slug: 'naogaon',
    canonicalName: 'Naogaon',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.7936,
    longitude: 88.9318,
  },
  {
    name: 'Natore',
    bnName: 'নাটোর',
    slug: 'natore',
    canonicalName: 'Natore',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.4206,
    longitude: 88.9324,
  },
  {
    name: 'Chapainawabganj',
    bnName: 'চাঁপাইনবাবগঞ্জ',
    slug: 'chapainawabganj',
    canonicalName: 'Chapai Nawabganj',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 24.5965,
    longitude: 88.2775,
  },
  {
    name: 'Joypurhat',
    bnName: 'জয়পুরহাট',
    slug: 'joypurhat',
    canonicalName: 'Jaipurhat',
    division: { name: 'Rajshahi', bnName: 'রাজশাহী', slug: 'rajshahi' },
    latitude: 25.1015,
    longitude: 89.0277,
  },

  // 6. Barishal (6)
  {
    name: 'Barishal',
    bnName: 'বরিশাল',
    slug: 'barishal',
    canonicalName: 'Barisal',
    division: { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
    latitude: 22.7010,
    longitude: 90.3535,
  },
  {
    name: 'Patuakhali',
    bnName: 'পটুয়াখালী',
    slug: 'patuakhali',
    canonicalName: 'Patuakhali',
    division: { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
    latitude: 22.3596,
    longitude: 90.3298,
  },
  {
    name: 'Bhola',
    bnName: 'ভোলা',
    slug: 'bhola',
    canonicalName: 'Bhola',
    division: { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
    latitude: 22.6859,
    longitude: 90.6481,
  },
  {
    name: 'Pirojpur',
    bnName: 'পিরোজপুর',
    slug: 'pirojpur',
    canonicalName: 'Pirojpur',
    division: { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
    latitude: 22.5841,
    longitude: 89.9720,
  },
  {
    name: 'Barguna',
    bnName: 'বরগুনা',
    slug: 'barguna',
    canonicalName: 'Borguna',
    division: { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
    latitude: 22.0953,
    longitude: 90.1121,
  },
  {
    name: 'Jhalokathi',
    bnName: 'ঝালকাঠি',
    slug: 'jhalokathi',
    canonicalName: 'Jhalokati',
    division: { name: 'Barishal', bnName: 'বরিশাল', slug: 'barishal' },
    latitude: 22.6406,
    longitude: 90.1987,
  },

  // 7. Rangpur (8)
  {
    name: 'Rangpur',
    bnName: 'রংপুর',
    slug: 'rangpur',
    canonicalName: 'Rangpur',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 25.7439,
    longitude: 89.2752,
  },
  {
    name: 'Dinajpur',
    bnName: 'দিনাজপুর',
    slug: 'dinajpur',
    canonicalName: 'Dinajpur',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 25.6217,
    longitude: 88.6355,
  },
  {
    name: 'Panchagarh',
    bnName: 'পঞ্চগড়',
    slug: 'panchagarh',
    canonicalName: 'Panchagarh',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 26.3411,
    longitude: 88.5542,
  },
  {
    name: 'Thakurgaon',
    bnName: 'ঠাকুরগাঁও',
    slug: 'thakurgaon',
    canonicalName: 'Thakurgaon',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 26.0337,
    longitude: 88.4617,
  },
  {
    name: 'Kurigram',
    bnName: 'কুড়িগ্রাম',
    slug: 'kurigram',
    canonicalName: 'Kurigram',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 25.8054,
    longitude: 89.6362,
  },
  {
    name: 'Gaibandha',
    bnName: 'গাইবান্ধা',
    slug: 'gaibandha',
    canonicalName: 'Gaibandha',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 25.3288,
    longitude: 89.5430,
  },
  {
    name: 'Nilphamari',
    bnName: 'নীলফামারী',
    slug: 'nilphamari',
    canonicalName: 'Nilfamari',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 25.9318,
    longitude: 88.8560,
  },
  {
    name: 'Lalmonirhat',
    bnName: 'লালমনিরহাট',
    slug: 'lalmonirhat',
    canonicalName: 'Lalmonirhat',
    division: { name: 'Rangpur', bnName: 'রংপুর', slug: 'rangpur' },
    latitude: 25.9923,
    longitude: 89.2847,
  },

  // 8. Mymensingh (4)
  {
    name: 'Mymensingh',
    bnName: 'ময়মনসিংহ',
    slug: 'mymensingh',
    canonicalName: 'Mymensingh',
    division: { name: 'Mymensingh', bnName: 'ময়মনসিংহ', slug: 'mymensingh' },
    latitude: 24.7471,
    longitude: 90.4203,
  },
  {
    name: 'Netrokona',
    bnName: 'নেত্রকোণা',
    slug: 'netrokona',
    canonicalName: 'Netrokona',
    division: { name: 'Mymensingh', bnName: 'ময়মনসিংহ', slug: 'mymensingh' },
    latitude: 24.8709,
    longitude: 90.7279,
  },
  {
    name: 'Sherpur',
    bnName: 'শেরপুর',
    slug: 'sherpur',
    canonicalName: 'Sherpur',
    division: { name: 'Mymensingh', bnName: 'ময়মনসিংহ', slug: 'mymensingh' },
    latitude: 25.0205,
    longitude: 90.0153,
  },
  {
    name: 'Jamalpur',
    bnName: 'জামালপুর',
    slug: 'jamalpur',
    canonicalName: 'Jamalpur',
    division: { name: 'Mymensingh', bnName: 'ময়মনসিংহ', slug: 'mymensingh' },
    latitude: 24.9375,
    longitude: 89.9378,
  },
];

// Helper maps for instantaneous lookups
export const STATIC_SLUG_TO_CANONICAL = new Map<string, ValidDistrict>();
export const STATIC_CANONICAL_TO_DISTRICT = new Map<ValidDistrict, District>();
export const STATIC_SLUG_TO_DISTRICT = new Map<string, District>();

ALL_STATIC_DISTRICTS.forEach((d) => {
  const districtObj: District = {
    id: `static-${d.slug}`,
    name: d.name,
    bnName: d.bnName,
    slug: d.slug,
    description: '',
    coverImage: '',
    latitude: d.latitude,
    longitude: d.longitude,
    division: {
      name: d.division.name,
      bnName: d.division.bnName,
      slug: d.division.slug,
    },
    _count: {
      places: 0,
    },
  };

  STATIC_SLUG_TO_CANONICAL.set(d.slug, d.canonicalName);
  STATIC_CANONICAL_TO_DISTRICT.set(d.canonicalName, districtObj);
  STATIC_SLUG_TO_DISTRICT.set(d.slug, districtObj);
});

export const ALL_STATIC_DISTRICTS_LIST: District[] = Array.from(STATIC_SLUG_TO_DISTRICT.values());
