export interface UpazilaInfo {
  name: string;
  bnName: string;
  slug: string;
}

/**
 * Official Thana / Upazila records for all 64 Districts of Bangladesh
 * Grouped by district slug (495+ total upazilas / thanas)
 */
export const DISTRICT_UPAZILAS_MAP: Record<string, UpazilaInfo[]> = {
  // ===================== DHAKA DIVISION (13 Districts) =====================
  dhaka: [
    { name: 'Dhanmondi', bnName: 'ধানমন্ডি', slug: 'dhanmondi' },
    { name: 'Mirpur', bnName: 'মিরপুর', slug: 'mirpur' },
    { name: 'Gulshan', bnName: 'গুলশান', slug: 'gulshan' },
    { name: 'Uttara', bnName: 'উত্তরা', slug: 'uttara' },
    { name: 'Mohammadpur', bnName: 'মোহাম্মদপুর', slug: 'mohammadpur' },
    { name: 'Savar', bnName: 'সাভার', slug: 'savar' },
    { name: 'Dhamrai', bnName: 'ধামরাই', slug: 'dhamrai' },
    { name: 'Keraniganj', bnName: 'কেরানীগঞ্জ', slug: 'keraniganj' },
    { name: 'Dohar', bnName: 'দোহার', slug: 'dohar' },
    { name: 'Nawabganj', bnName: 'নবাবগঞ্জ', slug: 'nawabganj' },
    { name: 'Tejgaon', bnName: 'তেজগাঁও', slug: 'tejgaon' },
    { name: 'Motijheel', bnName: 'মতিঝিল', slug: 'motijheel' },
    { name: 'Ramna', bnName: 'রমনা', slug: 'ramna' },
    { name: 'Lalbagh', bnName: 'লালবাগ', slug: 'lalbagh' },
    { name: 'Kotwali', bnName: 'কোতোয়ালী', slug: 'kotwali-dhaka' },
    { name: 'Sutrapur', bnName: 'সূত্রাপুর', slug: 'sutrapur' },
    { name: 'Shahbagh', bnName: 'শাহবাগ', slug: 'shahbagh' },
    { name: 'Banani', bnName: 'বনানী', slug: 'banani' },
    { name: 'Badda', bnName: 'বাড্ডা', slug: 'badda' },
    { name: 'Khilgaon', bnName: 'খিলগাঁও', slug: 'khilgaon' },
  ],
  gazipur: [
    { name: 'Gazipur Sadar', bnName: 'গাজীপুর সদর', slug: 'gazipur-sadar' },
    { name: 'Kaliakair', bnName: 'কালিয়াকৈর', slug: 'kaliakair' },
    { name: 'Kaliganj', bnName: 'কালীগঞ্জ', slug: 'kaliganj-gazipur' },
    { name: 'Kapasia', bnName: 'কাপাসিয়া', slug: 'kapasia' },
    { name: 'Sreepur', bnName: 'শ্রীপুর', slug: 'sreepur-gazipur' },
    { name: 'Tongi', bnName: 'টঙ্গী', slug: 'tongi' },
  ],
  narayanganj: [
    { name: 'Narayanganj Sadar', bnName: 'নারায়ণগঞ্জ সদর', slug: 'narayanganj-sadar' },
    { name: 'Araihazar', bnName: 'আড়াইহাজার', slug: 'araihazar' },
    { name: 'Bandar', bnName: 'বন্দর', slug: 'bandar' },
    { name: 'Rupganj', bnName: 'রূপগঞ্জ', slug: 'rupganj' },
    { name: 'Sonargaon', bnName: 'সোনারগাঁও', slug: 'sonargaon' },
    { name: 'Siddhirganj', bnName: 'সিদ্ধিরগঞ্জ', slug: 'siddhirganj' },
    { name: 'Fatullah', bnName: 'ফতুল্লা', slug: 'fatullah' },
  ],
  tangail: [
    { name: 'Tangail Sadar', bnName: 'টাঙ্গাইল সদর', slug: 'tangail-sadar' },
    { name: 'Basail', bnName: 'বাসাইল', slug: 'basail' },
    { name: 'Bhuapur', bnName: 'ভূঞাপুর', slug: 'bhuapur' },
    { name: 'Delduar', bnName: 'দেলদুয়ার', slug: 'delduar' },
    { name: 'Ghatail', bnName: 'ঘাটাইল', slug: 'ghatail' },
    { name: 'Gopalpur', bnName: 'গোপালপুর', slug: 'gopalpur' },
    { name: 'Kalihati', bnName: 'কালিহাতী', slug: 'kalihati' },
    { name: 'Madhupur', bnName: 'মধুপুর', slug: 'madhupur' },
    { name: 'Mirzapur', bnName: 'মির্জাপুর', slug: 'mirzapur' },
    { name: 'Nagarpur', bnName: 'নাগরপুর', slug: 'nagarpur' },
    { name: 'Sakhipur', bnName: 'সখিপুর', slug: 'sakhipur' },
    { name: 'Dhanbari', bnName: 'ধনবাড়ী', slug: 'dhanbari' },
  ],
  kishoreganj: [
    { name: 'Kishoreganj Sadar', bnName: 'কিশোরগঞ্জ সদর', slug: 'kishoreganj-sadar' },
    { name: 'Austagram', bnName: 'অষ্টগ্রাম', slug: 'austagram' },
    { name: 'Bajitpur', bnName: 'বাজিতপুর', slug: 'bajitpur' },
    { name: 'Bhairab', bnName: 'ভৈরব', slug: 'bhairab' },
    { name: 'Hossainpur', bnName: 'হোসেনপুর', slug: 'hossainpur' },
    { name: 'Itna', bnName: 'ইটনা', slug: 'itna' },
    { name: 'Karimganj', bnName: 'করিমগঞ্জ', slug: 'karimganj' },
    { name: 'Katiadi', bnName: 'কটিয়াদী', slug: 'katiadi' },
    { name: 'Kuliarchar', bnName: 'কুলিয়ারচর', slug: 'kuliarchar' },
    { name: 'Mithamain', bnName: 'মিঠামইন', slug: 'mithamain' },
    { name: 'Nikli', bnName: 'নিকলী', slug: 'nikli' },
    { name: 'Pakundia', bnName: 'পাকুন্দিয়া', slug: 'pakundia' },
    { name: 'Tarail', bnName: 'তাড়াইল', slug: 'tarail' },
  ],
  manikganj: [
    { name: 'Manikganj Sadar', bnName: 'মানিকগঞ্জ সদর', slug: 'manikganj-sadar' },
    { name: 'Daulatpur', bnName: 'দৌলতপুর', slug: 'daulatpur-manikganj' },
    { name: 'Ghior', bnName: 'ঘিওর', slug: 'ghior' },
    { name: 'Harirampur', bnName: 'হরিরামপুর', slug: 'harirampur' },
    { name: 'Saturia', bnName: 'সাটুরিয়া', slug: 'saturia' },
    { name: 'Shibalaya', bnName: 'শিবালয়', slug: 'shibalaya' },
    { name: 'Singair', bnName: 'সিংগাইর', slug: 'singair' },
  ],
  munshiganj: [
    { name: 'Munshiganj Sadar', bnName: 'মুন্সীগঞ্জ সদর', slug: 'munshiganj-sadar' },
    { name: 'Gazaria', bnName: 'গজারিয়া', slug: 'gazaria' },
    { name: 'Lohajang', bnName: 'লৌহজং', slug: 'lohajang' },
    { name: 'Sirajdikhan', bnName: 'সিরাজদিখান', slug: 'sirajdikhan' },
    { name: 'Sreenagar', bnName: 'শ্রীনগর', slug: 'sreenagar' },
    { name: 'Tongibari', bnName: 'টংগিবাড়ী', slug: 'tongibari' },
  ],
  narsingdi: [
    { name: 'Narsingdi Sadar', bnName: 'নরসিংদী সদর', slug: 'narsingdi-sadar' },
    { name: 'Belabo', bnName: 'বেলাব', slug: 'belabo' },
    { name: 'Monohardi', bnName: 'মনোহরদী', slug: 'monohardi' },
    { name: 'Palash', bnName: 'পলাশ', slug: 'palash' },
    { name: 'Raipura', bnName: 'রায়পুরা', slug: 'raipura' },
    { name: 'Shibpur', bnName: 'শিবপুর', slug: 'shibpur' },
  ],
  faridpur: [
    { name: 'Faridpur Sadar', bnName: 'ফরিদপুর সদর', slug: 'faridpur-sadar' },
    { name: 'Alfadanga', bnName: 'আলফাডাঙ্গা', slug: 'alfadanga' },
    { name: 'Bhanga', bnName: 'ভাঙ্গা', slug: 'bhanga' },
    { name: 'Boalmari', bnName: 'বোয়ালমারী', slug: 'boalmari' },
    { name: 'Charbhadrasan', bnName: 'চরভদ্রাসন', slug: 'charbhadrasan' },
    { name: 'Madhukhali', bnName: 'মধুখালী', slug: 'madhukhali' },
    { name: 'Nagarkanda', bnName: 'নগরকান্দা', slug: 'nagarkanda' },
    { name: 'Sadarpur', bnName: 'সদরপুর', slug: 'sadarpur' },
    { name: 'Saltha', bnName: 'সালথা', slug: 'saltha' },
  ],
  gopalganj: [
    { name: 'Gopalganj Sadar', bnName: 'গোপালগঞ্জ সদর', slug: 'gopalganj-sadar' },
    { name: 'Kashiani', bnName: 'কাশিয়ানী', slug: 'kashiani' },
    { name: 'Kotalipara', bnName: 'কোটালীপাড়া', slug: 'kotalipara' },
    { name: 'Muksudpur', bnName: 'মুকসুদপুর', slug: 'muksudpur' },
    { name: 'Tungipara', bnName: 'টুঙ্গিপাড়া', slug: 'tungipara' },
  ],
  madaripur: [
    { name: 'Madaripur Sadar', bnName: 'মাদারীপুর সদর', slug: 'madaripur-sadar' },
    { name: 'Kalkini', bnName: 'কালকিনি', slug: 'kalkini' },
    { name: 'Rajoir', bnName: 'রাজৈর', slug: 'rajoir' },
    { name: 'Shibchar', bnName: 'শিবচর', slug: 'shibchar' },
    { name: 'Dasar', bnName: 'ডাসার', slug: 'dasar' },
  ],
  rajbari: [
    { name: 'Rajbari Sadar', bnName: 'রাজবাড়ী সদর', slug: 'rajbari-sadar' },
    { name: 'Baliakandi', bnName: 'বালিয়াকান্দি', slug: 'baliakandi' },
    { name: 'Goalandaghat', bnName: 'গোয়ালন্দ', slug: 'goalanda' },
    { name: 'Pangsha', bnName: 'পাংশা', slug: 'pangsha' },
    { name: 'Kalukhali', bnName: 'কালুখালী', slug: 'kalukhali' },
  ],
  shariatpur: [
    { name: 'Shariatpur Sadar', bnName: 'শরীয়তপুর সদর', slug: 'shariatpur-sadar' },
    { name: 'Bhedarganj', bnName: 'ভেদরগঞ্জ', slug: 'bhedarganj' },
    { name: 'Damudya', bnName: 'ডামুড্যা', slug: 'damudya' },
    { name: 'Gosairhat', bnName: 'গোসাইরহাট', slug: 'gosairhat' },
    { name: 'Naria', bnName: 'নড়িয়া', slug: 'naria' },
    { name: 'Zajira', bnName: 'জাজিরা', slug: 'zajira' },
  ],

  // ===================== CHATTOGRAM DIVISION (11 Districts) =====================
  chattogram: [
    { name: 'Kotwali', bnName: 'কোতোয়ালী', slug: 'kotwali-ctg' },
    { name: 'Panchlaish', bnName: 'পাঁচলাইশ', slug: 'panchlaish' },
    { name: 'Patenga', bnName: 'পতেঙ্গা', slug: 'patenga' },
    { name: 'Sitakunda', bnName: 'সীতাকুণ্ড', slug: 'sitakunda' },
    { name: 'Mirsharai', bnName: 'মীরসরাই', slug: 'mirsharai' },
    { name: 'Hathazari', bnName: 'হাটহাজারী', slug: 'hathazari' },
    { name: 'Rangunia', bnName: 'রাঙ্গুনিয়া', slug: 'rangunia' },
    { name: 'Fatikchhari', bnName: 'ফটিকছড়ি', slug: 'fatikchhari' },
    { name: 'Raozan', bnName: 'রাউজান', slug: 'raozan' },
    { name: 'Patiya', bnName: 'পটিয়া', slug: 'patiya' },
    { name: 'Boalkhali', bnName: 'বোয়ালখালী', slug: 'boalkhali' },
    { name: 'Anwara', bnName: 'আনোয়ারা', slug: 'anwara' },
    { name: 'Chandanaish', bnName: 'চন্দনাইশ', slug: 'chandanaish' },
    { name: 'Satkania', bnName: 'সাতকানিয়া', slug: 'satkania' },
    { name: 'Lohagara', bnName: 'লোহাগাড়া', slug: 'lohagara-ctg' },
    { name: 'Banshkhali', bnName: 'বাঁশখালী', slug: 'banshkhali' },
    { name: 'Karnaphuli', bnName: 'কর্ণফুলী', slug: 'karnaphuli' },
    { name: 'Sandwip', bnName: 'সন্দ্বীপ', slug: 'sandwip' },
  ],
  'coxs-bazar': [
    { name: "Cox's Bazar Sadar", bnName: 'কক্সবাজার সদর', slug: 'coxs-bazar-sadar' },
    { name: 'Chakaria', bnName: 'চকোরিয়া', slug: 'chakaria' },
    { name: 'Kutubdia', bnName: 'কুতুবদিয়া', slug: 'kutubdia' },
    { name: 'Maheshkhali', bnName: 'মহেশখালী', slug: 'maheshkhali' },
    { name: 'Pekua', bnName: 'পেকুয়া', slug: 'pekua' },
    { name: 'Ramu', bnName: 'রামু', slug: 'ramu' },
    { name: 'Teknaf', bnName: 'টেকনাফ', slug: 'teknaf' },
    { name: 'Ukhia', bnName: 'উখিয়া', slug: 'ukhia' },
    { name: 'Eidgaon', bnName: 'ঈদগাঁও', slug: 'eidgaon' },
  ],
  bandarban: [
    { name: 'Bandarban Sadar', bnName: 'বান্দরবান সদর', slug: 'bandarban-sadar' },
    { name: 'Alikadam', bnName: 'আলীকদম', slug: 'alikadam' },
    { name: 'Lama', bnName: 'লামা', slug: 'lama' },
    { name: 'Naikhongchhari', bnName: 'নাইক্ষ্যংছড়ি', slug: 'naikhongchhari' },
    { name: 'Rowangchhari', bnName: 'রোয়াংছড়ি', slug: 'rowangchhari' },
    { name: 'Ruma', bnName: 'রুমা', slug: 'ruma' },
    { name: 'Thanchi', bnName: 'থানচি', slug: 'thanchi' },
  ],
  rangamati: [
    { name: 'Rangamati Sadar', bnName: 'রাঙ্গামাটি সদর', slug: 'rangamati-sadar' },
    { name: 'Baghaichhari', bnName: 'বাঘাইছড়ি', slug: 'baghaichhari' },
    { name: 'Barkal', bnName: 'বরকল', slug: 'barkal' },
    { name: 'Belaichhari', bnName: 'বিলাইছড়ি', slug: 'belaichhari' },
    { name: 'Juraichhari', bnName: 'জুরাইছড়ি', slug: 'juraichhari' },
    { name: 'Kaptai', bnName: 'কাপ্তাই', slug: 'kaptai' },
    { name: 'Kawkhali', bnName: 'কাউখালী', slug: 'kawkhali-rangamati' },
    { name: 'Langadu', bnName: 'লংগদু', slug: 'langadu' },
    { name: 'Naniarchar', bnName: 'নানিয়ারচর', slug: 'naniarchar' },
    { name: 'Rajasthali', bnName: 'রাজস্থলী', slug: 'rajasthali' },
  ],
  khagrachhari: [
    { name: 'Khagrachhari Sadar', bnName: 'খাগড়াছড়ি সদর', slug: 'khagrachhari-sadar' },
    { name: 'Dighinala', bnName: 'দীঘিনালা', slug: 'dighinala' },
    { name: 'Lakshmichhari', bnName: 'লক্ষ্মীছড়ি', slug: 'lakshmichhari' },
    { name: 'Mahalchhari', bnName: 'মহালছড়ি', slug: 'mahalchhari' },
    { name: 'Manikchhari', bnName: 'মানিকছড়ি', slug: 'manikchhari' },
    { name: 'Matiranga', bnName: 'মাটিরাঙ্গা', slug: 'matiranga' },
    { name: 'Panchhari', bnName: 'পানছড়ি', slug: 'panchhari' },
    { name: 'Ramgarh', bnName: 'রামগড়', slug: 'ramgarh' },
    { name: 'Guimara', bnName: 'গুইমারা', slug: 'guimara' },
  ],
  cumilla: [
    { name: 'Cumilla Adarsha Sadar', bnName: 'কুমিল্লা আদর্শ সদর', slug: 'cumilla-adarsha-sadar' },
    { name: 'Barura', bnName: 'বরুড়া', slug: 'barura' },
    { name: 'Brahmanpara', bnName: 'ব্রাহ্মণপাড়া', slug: 'brahmanpara' },
    { name: 'Burichang', bnName: 'বুড়িচং', slug: 'burichang' },
    { name: 'Chandina', bnName: 'চান্দিনা', slug: 'chandina' },
    { name: 'Chauddagram', bnName: 'চৌদ্দগ্রাম', slug: 'chauddagram' },
    { name: 'Daudkandi', bnName: 'দাউদকান্দি', slug: 'daudkandi' },
    { name: 'Debidwar', bnName: 'দেবিদ্বার', slug: 'debidwar' },
    { name: 'Homna', bnName: 'হোমনা', slug: 'homna' },
    { name: 'Laksam', bnName: 'লাকসাম', slug: 'laksam' },
    { name: 'Muradnagar', bnName: 'মুরাদনগর', slug: 'muradnagar' },
    { name: 'Nangalkot', bnName: 'নাঙ্গলকোট', slug: 'nangalkot' },
    { name: 'Meghna', bnName: 'মেঘনা', slug: 'meghna' },
    { name: 'Titas', bnName: 'তিতাস', slug: 'titas' },
    { name: 'Monohargonj', bnName: 'মনোহরগঞ্জ', slug: 'monohargonj' },
    { name: 'Lalmai', bnName: 'লালমাই', slug: 'lalmai' },
  ],
  brahmanbaria: [
    { name: 'Brahmanbaria Sadar', bnName: 'ব্রাহ্মণবাড়িয়া সদর', slug: 'brahmanbaria-sadar' },
    { name: 'Akhaura', bnName: 'আখাউড়া', slug: 'akhaura' },
    { name: 'Ashuganj', bnName: 'আশুগঞ্জ', slug: 'ashuganj' },
    { name: 'Bancharampur', bnName: 'বাঞ্ছারামপুর', slug: 'bancharampur' },
    { name: 'Bijoynagar', bnName: 'বিজয়নগর', slug: 'bijoynagar' },
    { name: 'Kasba', bnName: 'কসবা', slug: 'kasba' },
    { name: 'Nabinagar', bnName: 'নবীনগর', slug: 'nabinagar' },
    { name: 'Nasirnagar', bnName: 'নাসিরনগর', slug: 'nasirnagar' },
    { name: 'Sarail', bnName: 'সরাইল', slug: 'sarail' },
  ],
  chandpur: [
    { name: 'Chandpur Sadar', bnName: 'চাঁদপুর সদর', slug: 'chandpur-sadar' },
    { name: 'Faridganj', bnName: 'ফরিদগঞ্জ', slug: 'faridganj' },
    { name: 'Haimchar', bnName: 'হাইমচর', slug: 'haimchar' },
    { name: 'Hajiganj', bnName: 'হাজীগঞ্জ', slug: 'hajiganj' },
    { name: 'Kachua', bnName: 'কচুয়া', slug: 'kachua-chandpur' },
    { name: 'Matlab Dakshin', bnName: 'মতলব দক্ষিণ', slug: 'matlab-dakshin' },
    { name: 'Matlab Uttar', bnName: 'মতলব উত্তর', slug: 'matlab-uttar' },
    { name: 'Shahrasti', bnName: 'শাহরাস্তি', slug: 'shahrasti' },
  ],
  noakhali: [
    { name: 'Noakhali Sadar', bnName: 'নোয়াখালী সদর', slug: 'noakhali-sadar' },
    { name: 'Begumganj', bnName: 'বেগমগঞ্জ', slug: 'begumganj' },
    { name: 'Chatkhil', bnName: 'চাটখিল', slug: 'chatkhil' },
    { name: 'Companiganj', bnName: 'কোম্পানীগঞ্জ', slug: 'companiganj-noakhali' },
    { name: 'Hatiya', bnName: 'হাতিয়া', slug: 'hatiya' },
    { name: 'Kabirhat', bnName: 'কবিরহাট', slug: 'kabirhat' },
    { name: 'Senbagh', bnName: 'সেনবাগ', slug: 'senbagh' },
    { name: 'Sonaimuri', bnName: 'সোনাইমুড়ী', slug: 'sonaimuri' },
    { name: 'Subarnachar', bnName: 'সুবর্ণচর', slug: 'subarnachar' },
  ],
  feni: [
    { name: 'Feni Sadar', bnName: 'ফেনী সদর', slug: 'feni-sadar' },
    { name: 'Chhagalnaiya', bnName: 'ছাগলনাইয়া', slug: 'chhagalnaiya' },
    { name: 'Daganbhuiyan', bnName: 'দাগনভূঞা', slug: 'daganbhuiyan' },
    { name: 'Parshuram', bnName: 'পরশুরাম', slug: 'parshuram' },
    { name: 'Fulgazi', bnName: 'ফুলগাজী', slug: 'fulgazi' },
    { name: 'Sonagazi', bnName: 'সোনাগাজী', slug: 'sonagazi' },
  ],
  lakshmipur: [
    { name: 'Lakshmipur Sadar', bnName: 'লক্ষ্মীপুর সদর', slug: 'lakshmipur-sadar' },
    { name: 'Raipur', bnName: 'রায়পুর', slug: 'raipur' },
    { name: 'Ramganj', bnName: 'রামগঞ্জ', slug: 'ramganj' },
    { name: 'Ramgati', bnName: 'রামগতি', slug: 'ramgati' },
    { name: 'Kamalnagar', bnName: 'কমলনগর', slug: 'kamalnagar' },
  ],

  // ===================== SYLHET DIVISION (4 Districts) =====================
  sylhet: [
    { name: 'Sylhet Sadar', bnName: 'সিলেট সদর', slug: 'sylhet-sadar' },
    { name: 'Beanibazar', bnName: 'বিয়ানীবাজার', slug: 'beanibazar' },
    { name: 'Bishwanath', bnName: 'বিশ্বনাথ', slug: 'bishwanath' },
    { name: 'Companiganj', bnName: 'কোম্পানীগঞ্জ', slug: 'companiganj-sylhet' },
    { name: 'Fenchuganj', bnName: 'ফেঞ্চুগঞ্জ', slug: 'fenchuganj' },
    { name: 'Golapganj', bnName: 'গোলাপগঞ্জ', slug: 'golapganj' },
    { name: 'Gowainghat', bnName: 'গোয়াইনঘাট', slug: 'gowainghat' },
    { name: 'Jaintiapur', bnName: 'জৈন্তাপুর', slug: 'jaintiapur' },
    { name: 'Kanaighat', bnName: 'কানাইঘাট', slug: 'kanaighat' },
    { name: 'Zakiganj', bnName: 'জকিগঞ্জ', slug: 'zakiganj' },
    { name: 'Dakshin Surma', bnName: 'দক্ষিণ সুরমা', slug: 'dakshin-surma' },
    { name: 'Osmani Nagar', bnName: 'ওসমানীনগর', slug: 'osmani-nagar' },
    { name: 'Balaganj', bnName: 'বালাগঞ্জ', slug: 'balaganj' },
  ],
  moulvibazar: [
    { name: 'Moulvibazar Sadar', bnName: 'মৌলভীবাজার সদর', slug: 'moulvibazar-sadar' },
    { name: 'Barlekha', bnName: 'বড়লেখা', slug: 'barlekha' },
    { name: 'Juri', bnName: 'জুড়ী', slug: 'juri' },
    { name: 'Kamalganj', bnName: 'কমলগঞ্জ', slug: 'kamalganj' },
    { name: 'Kulaura', bnName: 'কুলাউড়া', slug: 'kulaura' },
    { name: 'Rajnagar', bnName: 'রাজনগর', slug: 'rajnagar' },
    { name: 'Sreemangal', bnName: 'শ্রীমঙ্গল', slug: 'sreemangal' },
  ],
  habiganj: [
    { name: 'Habiganj Sadar', bnName: 'হবিগঞ্জ সদর', slug: 'habiganj-sadar' },
    { name: 'Ajmiriganj', bnName: 'আজমিরীগঞ্জ', slug: 'ajmiriganj' },
    { name: 'Bahubal', bnName: 'বাহুবল', slug: 'bahubal' },
    { name: 'Baniachong', bnName: 'বানিয়াচং', slug: 'baniachong' },
    { name: 'Chunarughat', bnName: 'চুনারুঘাট', slug: 'chunarughat' },
    { name: 'Lakhai', bnName: 'লাখাই', slug: 'lakhai' },
    { name: 'Madhabpur', bnName: 'মাধবপুর', slug: 'madhabpur' },
    { name: 'Nabiganj', bnName: 'নবীগঞ্জ', slug: 'nabiganj' },
    { name: 'Sayestaganj', bnName: 'শায়েস্তাগঞ্জ', slug: 'sayestaganj' },
  ],
  sunamganj: [
    { name: 'Sunamganj Sadar', bnName: 'সুনামগঞ্জ সদর', slug: 'sunamganj-sadar' },
    { name: 'Bishwamvarpur', bnName: 'বিশ্বম্ভরপুর', slug: 'bishwamvarpur' },
    { name: 'Chhatak', bnName: 'ছাতক', slug: 'chhatak' },
    { name: 'Derai', bnName: 'দিরাই', slug: 'derai' },
    { name: 'Dharampasha', bnName: 'ধর্মপাশা', slug: 'dharampasha' },
    { name: 'Dowarabazar', bnName: 'দোয়ারাবাজার', slug: 'dowarabazar' },
    { name: 'Jagannathpur', bnName: 'জগন্নাথপুর', slug: 'jagannathpur' },
    { name: 'Jamalganj', bnName: 'জামালগঞ্জ', slug: 'jamalganj' },
    { name: 'Sulla', bnName: 'শাল্লা', slug: 'sulla' },
    { name: 'Tahirpur', bnName: 'তাহিরপুর', slug: 'tahirpur' },
    { name: 'Shantiganj', bnName: 'শান্তিগঞ্জ', slug: 'shantiganj' },
    { name: 'Madhyanagar', bnName: 'মধ্যনগর', slug: 'madhyanagar' },
  ],

  // ===================== KHULNA DIVISION (10 Districts) =====================
  khulna: [
    { name: 'Koyra', bnName: 'কয়রা', slug: 'koyra' },
    { name: 'Dacope', bnName: 'দাকোপ', slug: 'dacope' },
    { name: 'Dumuria', bnName: 'ডুমুরিয়া', slug: 'dumuria' },
    { name: 'Dighalia', bnName: 'দিঘলিয়া', slug: 'dighalia' },
    { name: 'Paikgachha', bnName: 'পাইকগাছা', slug: 'paikgachha' },
    { name: 'Phultala', bnName: 'ফুলতলা', slug: 'phultala' },
    { name: 'Batiaghata', bnName: 'বটিয়াঘাটা', slug: 'batiaghata' },
    { name: 'Rupsha', bnName: 'রূপসা', slug: 'rupsha' },
    { name: 'Terokhada', bnName: 'তেরখাদা', slug: 'terokhada' },
    { name: 'Khalishpur', bnName: 'খালিশপুর', slug: 'khalishpur' },
    { name: 'Sonadanga', bnName: 'সোনাডাঙ্গা', slug: 'sonadanga' },
    { name: 'Kotwali', bnName: 'কোতোয়ালী', slug: 'kotwali-khulna' },
  ],
  bagerhat: [
    { name: 'Bagerhat Sadar', bnName: 'বাগেরহাট সদর', slug: 'bagerhat-sadar' },
    { name: 'Chitalmari', bnName: 'চিতলমারী', slug: 'chitalmari' },
    { name: 'Fakirhat', bnName: 'ফকিরহাট', slug: 'fakirhat' },
    { name: 'Kachua', bnName: 'কচুয়া', slug: 'kachua-bagerhat' },
    { name: 'Mollahat', bnName: 'মোল্লাহাট', slug: 'mollahat' },
    { name: 'Mongla', bnName: 'মোংলা', slug: 'mongla' },
    { name: 'Morrelganj', bnName: 'মোরেলগঞ্জ', slug: 'morrelganj' },
    { name: 'Rampal', bnName: 'রামপাল', slug: 'rampal' },
    { name: 'Sarankhola', bnName: 'শরণখোলা', slug: 'sarankhola' },
  ],
  satkhira: [
    { name: 'Satkhira Sadar', bnName: 'সাতক্ষীরা সদর', slug: 'satkhira-sadar' },
    { name: 'Assasuni', bnName: 'আশাশুনি', slug: 'assasuni' },
    { name: 'Debhata', bnName: 'দেবহাটা', slug: 'debhata' },
    { name: 'Kalaroa', bnName: 'কলারোয়া', slug: 'kalaroa' },
    { name: 'Kaliganj', bnName: 'কালীগঞ্জ', slug: 'kaliganj-satkhira' },
    { name: 'Shyamnagar', bnName: 'শ্যামনগর', slug: 'shyamnagar' },
    { name: 'Tala', bnName: 'তালা', slug: 'tala' },
  ],
  jashore: [
    { name: 'Jashore Sadar', bnName: 'যশোর সদর', slug: 'jashore-sadar' },
    { name: 'Abhaynagar', bnName: 'অভয়নগর', slug: 'abhaynagar' },
    { name: 'Bagherpara', bnName: 'বাঘারপাড়া', slug: 'bagherpara' },
    { name: 'Chaugachha', bnName: 'চৌগাছা', slug: 'chaugachha' },
    { name: 'Jhikargachha', bnName: 'ঝিকরগাছা', slug: 'jhikargachha' },
    { name: 'Keshabpur', bnName: 'কেশবপুর', slug: 'keshabpur' },
    { name: 'Manirampur', bnName: 'মণিরামপুর', slug: 'manirampur' },
    { name: 'Sharsha', bnName: 'শার্শা', slug: 'sharsha' },
  ],
  kushtia: [
    { name: 'Kushtia Sadar', bnName: 'কুষ্টিয়া সদর', slug: 'kushtia-sadar' },
    { name: 'Bheramara', bnName: 'ভেড়ামারা', slug: 'bheramara' },
    { name: 'Daulatpur', bnName: 'দৌলতপুর', slug: 'daulatpur-kushtia' },
    { name: 'Khoksa', bnName: 'খোকসা', slug: 'khoksa' },
    { name: 'Kumarkhali', bnName: 'কুমারখালী', slug: 'kumarkhali' },
    { name: 'Mirpur', bnName: 'মিরপুর', slug: 'mirpur-kushtia' },
  ],
  jhenaidah: [
    { name: 'Jhenaidah Sadar', bnName: 'ঝিনাইদহ সদর', slug: 'jhenaidah-sadar' },
    { name: 'Harinakunda', bnName: 'হরিণাকুণ্ডু', slug: 'harinakunda' },
    { name: 'Kaliganj', bnName: 'কালীগঞ্জ', slug: 'kaliganj-jhenaidah' },
    { name: 'Kotchandpur', bnName: 'কোটচাঁদপুর', slug: 'kotchandpur' },
    { name: 'Maheshpur', bnName: 'মহেশপুর', slug: 'maheshpur' },
    { name: 'Shailkupa', bnName: 'শৈলকুপা', slug: 'shailkupa' },
  ],
  chuadanga: [
    { name: 'Chuadanga Sadar', bnName: 'চুয়াডাঙ্গা সদর', slug: 'chuadanga-sadar' },
    { name: 'Alamdanga', bnName: 'আলমডাঙ্গা', slug: 'alamdanga' },
    { name: 'Damurhuda', bnName: 'দামুড়হুদা', slug: 'damurhuda' },
    { name: 'Jibannagar', bnName: 'জীবননগর', slug: 'jibannagar' },
  ],
  meherpur: [
    { name: 'Meherpur Sadar', bnName: 'মেহেরপুর সদর', slug: 'meherpur-sadar' },
    { name: 'Gangni', bnName: 'গাংনী', slug: 'gangni' },
    { name: 'Mujibnagar', bnName: 'মুজিবনগর', slug: 'mujibnagar' },
  ],
  narail: [
    { name: 'Narail Sadar', bnName: 'নড়াইল সদর', slug: 'narail-sadar' },
    { name: 'Kalia', bnName: 'কালিয়া', slug: 'kalia' },
    { name: 'Lohagara', bnName: 'লোহাগড়া', slug: 'lohagara-narail' },
  ],
  magura: [
    { name: 'Magura Sadar', bnName: 'মাগুরা সদর', slug: 'magura-sadar' },
    { name: 'Mohammadpur', bnName: 'মহম্মদপুর', slug: 'mohammadpur-magura' },
    { name: 'Shalikha', bnName: 'শালিখা', slug: 'shalikha' },
    { name: 'Sreepur', bnName: 'শ্রীপুর', slug: 'sreepur-magura' },
  ],

  // ===================== RAJSHAHI DIVISION (8 Districts) =====================
  rajshahi: [
    { name: 'Boalia', bnName: 'বোয়ালিয়া', slug: 'boalia' },
    { name: 'Rajpara', bnName: 'রাজপাড়া', slug: 'rajpara' },
    { name: 'Motihar', bnName: 'মতিহার', slug: 'motihar' },
    { name: 'Shah Makhdum', bnName: 'শাহ মখদুম', slug: 'shah-makhdum' },
    { name: 'Paba', bnName: 'পবা', slug: 'paba' },
    { name: 'Puthia', bnName: 'পুঠিয়া', slug: 'puthia' },
    { name: 'Bagha', bnName: 'বাঘা', slug: 'bagha' },
    { name: 'Charghat', bnName: 'চারঘাট', slug: 'charghat' },
    { name: 'Durgapur', bnName: 'দুর্গাপুর', slug: 'durgapur-rajshahi' },
    { name: 'Godagari', bnName: 'গোদাগাড়ী', slug: 'godagari' },
    { name: 'Mohanpur', bnName: 'মোহনপুর', slug: 'mohanpur' },
    { name: 'Tanore', bnName: 'তানোর', slug: 'tanore' },
    { name: 'Bagmara', bnName: 'বাগমারা', slug: 'bagmara' },
  ],
  bogura: [
    { name: 'Bogura Sadar', bnName: 'বগুড়া সদর', slug: 'bogura-sadar' },
    { name: 'Adamdighi', bnName: 'আদমদীঘি', slug: 'adamdighi' },
    { name: 'Dhunat', bnName: 'ধুনট', slug: 'dhunat' },
    { name: 'Dupchanchia', bnName: 'দুপচাঁচিয়া', slug: 'dupchanchia' },
    { name: 'Gabtali', bnName: 'গাবতলী', slug: 'gabtali' },
    { name: 'Kahaloo', bnName: 'কাহালু', slug: 'kahaloo' },
    { name: 'Nandigram', bnName: 'নন্দীগ্রাম', slug: 'nandigram' },
    { name: 'Sariakandi', bnName: 'সারিয়াকান্দি', slug: 'sariakandi' },
    { name: 'Shajahanpur', bnName: 'শাজাহানপুর', slug: 'shajahanpur' },
    { name: 'Sherpur', bnName: 'শেরপুর', slug: 'sherpur-bogura' },
    { name: 'Shibganj', bnName: 'শিবগঞ্জ', slug: 'shibganj-bogura' },
    { name: 'Sonatala', bnName: 'সোনাতলা', slug: 'sonatala' },
  ],
  pabna: [
    { name: 'Pabna Sadar', bnName: 'পাবনা সদর', slug: 'pabna-sadar' },
    { name: 'Atgharia', bnName: 'আটঘরিয়া', slug: 'atgharia' },
    { name: 'Bera', bnName: 'বেড়া', slug: 'bera' },
    { name: 'Bhangura', bnName: 'ভাঙ্গুড়া', slug: 'bhangura' },
    { name: 'Chatmohar', bnName: 'চাটমোহর', slug: 'chatmohar' },
    { name: 'Faridpur', bnName: 'ফরিদপুর', slug: 'faridpur-pabna' },
    { name: 'Ishwardi', bnName: 'ঈশ্বরদী', slug: 'ishwardi' },
    { name: 'Santhia', bnName: 'সাঁথিয়া', slug: 'santhia' },
    { name: 'Sujanagar', bnName: 'সুজানগর', slug: 'sujanagar' },
  ],
  sirajganj: [
    { name: 'Sirajganj Sadar', bnName: 'সিরাজগঞ্জ সদর', slug: 'sirajganj-sadar' },
    { name: 'Belkuchi', bnName: 'বেলকুচি', slug: 'belkuchi' },
    { name: 'Chauhali', bnName: 'চৌহালী', slug: 'chauhali' },
    { name: 'Kamarkhanda', bnName: 'কামারখন্দ', slug: 'kamarkhanda' },
    { name: 'Kazipur', bnName: 'কাজীপুর', slug: 'kazipur' },
    { name: 'Raiganj', bnName: 'রায়গঞ্জ', slug: 'raiganj' },
    { name: 'Shahjadpur', bnName: 'শাহজাদপুর', slug: 'shahjadpur' },
    { name: 'Tarash', bnName: 'তাড়াশ', slug: 'tarash' },
    { name: 'Ullahpara', bnName: 'উল্লাপাড়া', slug: 'ullahpara' },
  ],
  naogaon: [
    { name: 'Naogaon Sadar', bnName: 'নওগাঁ সদর', slug: 'naogaon-sadar' },
    { name: 'Atrai', bnName: 'আত্রাই', slug: 'atrai' },
    { name: 'Badalgachhi', bnName: 'বদলগাছী', slug: 'badalgachhi' },
    { name: 'Dhamoirhat', bnName: 'ধামইরহাট', slug: 'dhamoirhat' },
    { name: 'Manda', bnName: 'মান্দা', slug: 'manda' },
    { name: 'Mohadevpur', bnName: 'মহাদেবপুর', slug: 'mohadevpur' },
    { name: 'Niamatpur', bnName: 'নিয়ামতপুর', slug: 'niamatpur' },
    { name: 'Patnitala', bnName: 'পত্নীতলা', slug: 'patnitala' },
    { name: 'Porsha', bnName: 'পোরশা', slug: 'porsha' },
    { name: 'Raninagar', bnName: 'রানীনগর', slug: 'raninagar' },
    { name: 'Sapahar', bnName: 'সাপাহার', slug: 'sapahar' },
  ],
  natore: [
    { name: 'Natore Sadar', bnName: 'নাটোর সদর', slug: 'natore-sadar' },
    { name: 'Bagatipara', bnName: 'বাগাতিপাড়া', slug: 'bagatipara' },
    { name: 'Baraigram', bnName: 'বড়াইগ্রাম', slug: 'baraigram' },
    { name: 'Gurudaspur', bnName: 'গুরুদাসপুর', slug: 'gurudaspur' },
    { name: 'Lalpur', bnName: 'লালপুর', slug: 'lalpur' },
    { name: 'Naldanga', bnName: 'নলডাঙ্গা', slug: 'naldanga' },
    { name: 'Singra', bnName: 'সিংড়া', slug: 'singra' },
  ],
  chapainawabganj: [
    { name: 'Chapainawabganj Sadar', bnName: 'চাঁপাইনবাবগঞ্জ সদর', slug: 'chapainawabganj-sadar' },
    { name: 'Bholahat', bnName: 'ভোলাহাট', slug: 'bholahat' },
    { name: 'Gomastapur', bnName: 'গোমস্তাপুর', slug: 'gomastapur' },
    { name: 'Nachole', bnName: 'নাচোল', slug: 'nachole' },
    { name: 'Shibganj', bnName: 'শিবগঞ্জ', slug: 'shibganj-chapainawabganj' },
  ],
  joypurhat: [
    { name: 'Joypurhat Sadar', bnName: 'জয়পুরহাট সদর', slug: 'joypurhat-sadar' },
    { name: 'Akkelpur', bnName: 'আক্কেলপুর', slug: 'akkelpur' },
    { name: 'Kalai', bnName: 'কালাই', slug: 'kalai' },
    { name: 'Khetlal', bnName: 'ক্ষেতলাল', slug: 'khetlal' },
    { name: 'Panchbibi', bnName: 'পাঁচবিবি', slug: 'panchbibi' },
  ],

  // ===================== BARISHAL DIVISION (6 Districts) =====================
  barishal: [
    { name: 'Barishal Sadar', bnName: 'বরিশাল সদর', slug: 'barishal-sadar' },
    { name: 'Agailjhara', bnName: 'আগৈলঝাড়া', slug: 'agailjhara' },
    { name: 'Babuganj', bnName: 'বাবুগঞ্জ', slug: 'babuganj' },
    { name: 'Bakerganj', bnName: 'বাকেরগঞ্জ', slug: 'bakerganj' },
    { name: 'Banaripara', bnName: 'বানারীপাড়া', slug: 'banaripara' },
    { name: 'Gaurnadi', bnName: 'গৌরনদী', slug: 'gaurnadi' },
    { name: 'Hizla', bnName: 'হিজলা', slug: 'hizla' },
    { name: 'Mehendiganj', bnName: 'মেহেন্দিগঞ্জ', slug: 'mehendiganj' },
    { name: 'Muladi', bnName: 'মুলাদী', slug: 'muladi' },
    { name: 'Wazirpur', bnName: 'উজিরপুর', slug: 'wazirpur' },
  ],
  patuakhali: [
    { name: 'Patuakhali Sadar', bnName: 'পটুয়াখালী সদর', slug: 'patuakhali-sadar' },
    { name: 'Bauphal', bnName: 'বাউফল', slug: 'bauphal' },
    { name: 'Dashmina', bnName: 'দশমিনা', slug: 'dashmina' },
    { name: 'Galachipa', bnName: 'গলাচিপা', slug: 'galachipa' },
    { name: 'Kalapara (Kuakata)', bnName: 'কলাপাড়া (কুয়াকাটা)', slug: 'kalapara' },
    { name: 'Mirzaganj', bnName: 'মির্জাগঞ্জ', slug: 'mirzaganj' },
    { name: 'Rangabali', bnName: 'রাঙ্গাবালী', slug: 'rangabali' },
    { name: 'Dumki', bnName: 'দুমকি', slug: 'dumki' },
  ],
  bhola: [
    { name: 'Bhola Sadar', bnName: 'ভোলা সদর', slug: 'bhola-sadar' },
    { name: 'Burhanuddin', bnName: 'বোরহানউদ্দিন', slug: 'burhanuddin' },
    { name: 'Char Fasson', bnName: 'চরফ্যাশন', slug: 'char-fasson' },
    { name: 'Daulatkhan', bnName: 'দৌলতখান', slug: 'daulatkhan' },
    { name: 'Lalmohan', bnName: 'লালমোহন', slug: 'lalmohan' },
    { name: 'Manpura', bnName: 'মনপুরা', slug: 'manpura' },
    { name: 'Tazumuddin', bnName: 'তজুমদ্দিন', slug: 'tazumuddin' },
  ],
  pirojpur: [
    { name: 'Pirojpur Sadar', bnName: 'পিরোজপুর সদর', slug: 'pirojpur-sadar' },
    { name: 'Bhandaria', bnName: 'ভান্ডারিয়া', slug: 'bhandaria' },
    { name: 'Kawkhali', bnName: 'কাউখালী', slug: 'kawkhali-pirojpur' },
    { name: 'Mathbaria', bnName: 'মঠবাড়িয়া', slug: 'mathbaria' },
    { name: 'Nazirpur', bnName: 'নাজিরপুর', slug: 'nazirpur' },
    { name: 'Nesarabad (Swarupkati)', bnName: 'নেছারাবাদ (স্বরূপকাঠি)', slug: 'nesarabad' },
    { name: 'Indurkani', bnName: 'ইন্দুরকানী', slug: 'indurkani' },
  ],
  barguna: [
    { name: 'Barguna Sadar', bnName: 'বরগুনা সদর', slug: 'barguna-sadar' },
    { name: 'Amtali', bnName: 'আমতলী', slug: 'amtali' },
    { name: 'Bamna', bnName: 'বামনা', slug: 'bamna' },
    { name: 'Betagi', bnName: 'বেতাগী', slug: 'betagi' },
    { name: 'Patharghata', bnName: 'পাথরঘাটা', slug: 'patharghata' },
    { name: 'Taltali', bnName: 'তালতলী', slug: 'taltali' },
  ],
  jhalokathi: [
    { name: 'Jhalokathi Sadar', bnName: 'ঝালকাঠি সদর', slug: 'jhalokathi-sadar' },
    { name: 'Kathalia', bnName: 'কাঁঠালিয়া', slug: 'kathalia' },
    { name: 'Nalchhiti', bnName: 'নলছিটি', slug: 'nalchhiti' },
    { name: 'Rajapur', bnName: 'রাজাপুর', slug: 'rajapur' },
  ],

  // ===================== RANGPUR DIVISION (8 Districts) =====================
  rangpur: [
    { name: 'Rangpur Sadar', bnName: 'রংপুর সদর', slug: 'rangpur-sadar' },
    { name: 'Badarganj', bnName: 'বদরগঞ্জ', slug: 'badarganj' },
    { name: 'Gangachhara', bnName: 'গংগাচড়া', slug: 'gangachhara' },
    { name: 'Kaunia', bnName: 'কাউনিয়া', slug: 'kaunia' },
    { name: 'Mithapukur', bnName: 'মিঠাপুকুর', slug: 'mithapukur' },
    { name: 'Pirgachha', bnName: 'পীরগাছা', slug: 'pirgachha' },
    { name: 'Pirganj', bnName: 'পীরগঞ্জ', slug: 'pirganj-rangpur' },
    { name: 'Taraganj', bnName: 'তারাগঞ্জ', slug: 'taraganj' },
  ],
  dinajpur: [
    { name: 'Dinajpur Sadar', bnName: 'দিনাজপুর সদর', slug: 'dinajpur-sadar' },
    { name: 'Birampur', bnName: 'বিরামপুর', slug: 'birampur' },
    { name: 'Birganj', bnName: 'বীরগঞ্জ', slug: 'birganj' },
    { name: 'Biral', bnName: 'বিরল', slug: 'biral' },
    { name: 'Bochaganj', bnName: 'বোচাগঞ্জ', slug: 'bochaganj' },
    { name: 'Chirirbandar', bnName: 'চিরিরবন্দর', slug: 'chirirbandar' },
    { name: 'Phulbari', bnName: 'ফুলবাড়ী', slug: 'phulbari-dinajpur' },
    { name: 'Ghoraghat', bnName: 'ঘোড়াঘাট', slug: 'ghoraghat' },
    { name: 'Hakimpur', bnName: 'হাকিমপুর', slug: 'hakimpur' },
    { name: 'Kaharole', bnName: 'কাহারোল (কান্তজীউ)', slug: 'kaharole' },
    { name: 'Khansama', bnName: 'খানসামা', slug: 'khansama' },
    { name: 'Nawabganj', bnName: 'নবাবগঞ্জ', slug: 'nawabganj-dinajpur' },
    { name: 'Parbatipur', bnName: 'পার্বতীপুর', slug: 'parbatipur' },
  ],
  panchagarh: [
    { name: 'Panchagarh Sadar', bnName: 'পঞ্চগড় সদর', slug: 'panchagarh-sadar' },
    { name: 'Atwari', bnName: 'আটোয়ারী', slug: 'atwari' },
    { name: 'Boda', bnName: 'বোদা', slug: 'boda' },
    { name: 'Debiganj', bnName: 'দেবীগঞ্জ', slug: 'debiganj' },
    { name: 'Tetulia', bnName: 'তেঁতুলিয়া', slug: 'tetulia' },
  ],
  thakurgaon: [
    { name: 'Thakurgaon Sadar', bnName: 'ঠাকুরগাঁও সদর', slug: 'thakurgaon-sadar' },
    { name: 'Baliadangi', bnName: 'বালিয়াডাঙ্গী', slug: 'baliadangi' },
    { name: 'Haripur', bnName: 'হরিপুর', slug: 'haripur' },
    { name: 'Pirganj', bnName: 'পীরগঞ্জ', slug: 'pirganj-thakurgaon' },
    { name: 'Ranisankail', bnName: 'রাণীশংকৈল', slug: 'ranisankail' },
  ],
  kurigram: [
    { name: 'Kurigram Sadar', bnName: 'কুড়িগ্রাম সদর', slug: 'kurigram-sadar' },
    { name: 'Bhurungamari', bnName: 'ভূরুঙ্গামারী', slug: 'bhurungamari' },
    { name: 'Char Rajibpur', bnName: 'চর রাজিবপুর', slug: 'char-rajibpur' },
    { name: 'Chilmari', bnName: 'চিলমারী', slug: 'chilmari' },
    { name: 'Phulbari', bnName: 'ফুলবাড়ী', slug: 'phulbari-kurigram' },
    { name: 'Nageshwari', bnName: 'নাগেশ্বরী', slug: 'nageshwari' },
    { name: 'Rajarhat', bnName: 'রাজারহাট', slug: 'rajarhat' },
    { name: 'Raomari', bnName: 'রৌমারী', slug: 'raomari' },
    { name: 'Ulipur', bnName: 'উলিপুর', slug: 'ulipur' },
  ],
  gaibandha: [
    { name: 'Gaibandha Sadar', bnName: 'গাইবান্ধা সদর', slug: 'gaibandha-sadar' },
    { name: 'Fulchhari', bnName: 'ফুলছড়ি', slug: 'fulchhari' },
    { name: 'Gobindaganj', bnName: 'গোবিন্দগঞ্জ', slug: 'gobindaganj' },
    { name: 'Palashbari', bnName: 'পলাশবাড়ী', slug: 'palashbari' },
    { name: 'Sadullapur', bnName: 'সাদুল্লাপুর', slug: 'sadullapur' },
    { name: 'Saghata', bnName: 'সাঘাটা', slug: 'saghata' },
    { name: 'Sundarganj', bnName: 'সুন্দরগঞ্জ', slug: 'sundarganj' },
  ],
  nilphamari: [
    { name: 'Nilphamari Sadar', bnName: 'নীলফামারী সদর', slug: 'nilphamari-sadar' },
    { name: 'Dimla', bnName: 'ডিমলা', slug: 'dimla' },
    { name: 'Domar', bnName: 'ডোমার', slug: 'domar' },
    { name: 'Jaldhaka', bnName: 'জলঢাকা', slug: 'jaldhaka' },
    { name: 'Kishoreganj', bnName: 'কিশোরগঞ্জ', slug: 'kishoreganj-nilphamari' },
    { name: 'Saidpur', bnName: 'সৈয়দপুর', slug: 'saidpur' },
  ],
  lalmonirhat: [
    { name: 'Lalmonirhat Sadar', bnName: 'লালমনিরহাট সদর', slug: 'lalmonirhat-sadar' },
    { name: 'Aditmari', bnName: 'আদিতমারী', slug: 'aditmari' },
    { name: 'Hatibandha', bnName: 'হাতীবান্ধা', slug: 'hatibandha' },
    { name: 'Kaliganj', bnName: 'কালীগঞ্জ', slug: 'kaliganj-lalmonirhat' },
    { name: 'Patgram', bnName: 'পাটগ্রাম', slug: 'patgram' },
  ],

  // ===================== MYMENSINGH DIVISION (4 Districts) =====================
  mymensingh: [
    { name: 'Mymensingh Sadar', bnName: 'ময়মনসিংহ সদর', slug: 'mymensingh-sadar' },
    { name: 'Bhaluka', bnName: 'ভালুকা', slug: 'bhaluka' },
    { name: 'Dhobaura', bnName: 'ধোবাউড়া', slug: 'dhobaura' },
    { name: 'Fulbaria', bnName: 'ফুলবাড়িয়া', slug: 'fulbaria' },
    { name: 'Gafargaon', bnName: 'গফরগাঁও', slug: 'gafargaon' },
    { name: 'Gauripur', bnName: 'গৌরীপুর', slug: 'gauripur' },
    { name: 'Haluaghat', bnName: 'হালুয়াঘাট', slug: 'haluaghat' },
    { name: 'Ishwarganj', bnName: 'ঈশ্বরগঞ্জ', slug: 'ishwarganj' },
    { name: 'Muktagachha', bnName: 'মুক্তাগাছা', slug: 'muktagachha' },
    { name: 'Nandail', bnName: 'নান্দাইল', slug: 'nandail' },
    { name: 'Phulpur', bnName: 'ফুলপুর', slug: 'phulpur' },
    { name: 'Tarakanda', bnName: 'তারাকান্দা', slug: 'tarakanda' },
    { name: 'Trishal', bnName: 'ত্রিশাল', slug: 'trishal' },
  ],
  jamalpur: [
    { name: 'Jamalpur Sadar', bnName: 'জামালপুর সদর', slug: 'jamalpur-sadar' },
    { name: 'Bakshiganj', bnName: 'বকশীগঞ্জ', slug: 'bakshiganj' },
    { name: 'Dewanganj', bnName: 'দেওয়ানগঞ্জ', slug: 'dewanganj' },
    { name: 'Islampur', bnName: 'ইসলামপুর', slug: 'islampur' },
    { name: 'Madarganj', bnName: 'মাদারগঞ্জ', slug: 'madarganj' },
    { name: 'Melandaha', bnName: 'মেলান্দহ', slug: 'melandaha' },
    { name: 'Sarishabari', bnName: 'সরিষাবাড়ী', slug: 'sarishabari' },
  ],
  netrokona: [
    { name: 'Netrokona Sadar', bnName: 'নেত্রকোণা সদর', slug: 'netrokona-sadar' },
    { name: 'Atpara', bnName: 'আটপাড়া', slug: 'atpara' },
    { name: 'Barhatta', bnName: 'বারহাট্টা', slug: 'barhatta' },
    { name: 'Durgapur (Birishiri)', bnName: 'দুর্গাপুর (বিরিশিরি)', slug: 'durgapur-netrokona' },
    { name: 'Kalmakanda', bnName: 'কলমাকান্দা', slug: 'kalmakanda' },
    { name: 'Kendua', bnName: 'কেন্দুয়া', slug: 'kendua' },
    { name: 'Khaliajuri', bnName: 'খালিয়াজুড়ী', slug: 'khaliajuri' },
    { name: 'Madan', bnName: 'মদন', slug: 'madan' },
    { name: 'Mohanganj', bnName: 'মোহনগঞ্জ', slug: 'mohanganj' },
    { name: 'Purbadhala', bnName: 'পূর্বধলা', slug: 'purbadhala' },
  ],
  sherpur: [
    { name: 'Sherpur Sadar', bnName: 'শেরপুর সদর', slug: 'sherpur-sadar' },
    { name: 'Jhenaigati', bnName: 'ঝিনাইগাতী', slug: 'jhenaigati' },
    { name: 'Nakla', bnName: 'নকলা', slug: 'nakla' },
    { name: 'Nalitabari', bnName: 'নালিতাবাড়ী', slug: 'nalitabari' },
    { name: 'Sreebardi', bnName: 'শ্রীবরদী', slug: 'sreebardi' },
  ],
};

/**
 * Returns list of Upazilas/Thanas for a given district slug.
 * Fallbacks to empty array if unknown.
 */
export function getDistrictUpazilas(districtSlug: string): UpazilaInfo[] {
  if (!districtSlug) return [];
  const normalized = districtSlug.toLowerCase().trim();
  return DISTRICT_UPAZILAS_MAP[normalized] || [];
}

/**
 * Total Upazila / Thana count across Bangladesh
 */
export function getTotalUpazilasCount(): number {
  return Object.values(DISTRICT_UPAZILAS_MAP).reduce((sum, list) => sum + list.length, 0);
}

/**
 * Resolves the Upazila/Thana name for a place
 */
export function resolvePlaceUpazila(
  place: {
    name?: string;
    bnName?: string | null;
    description?: string;
    thana?: string | null;
    upazila?: string | null;
  },
  districtSlug: string
): string | null {
  if (place.thana) return place.thana;
  if (place.upazila) return place.upazila;
  const upazilas = getDistrictUpazilas(districtSlug);
  if (!upazilas.length) return null;
  const text = `${place.name || ''} ${place.bnName || ''} ${place.description || ''}`.toLowerCase();
  for (const u of upazilas) {
    if (text.includes(u.name.toLowerCase()) || text.includes(u.bnName)) {
      return u.bnName;
    }
  }
  return null;
}

